services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - 'redis-data:/data'

#  app:
#    container_name: app
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#      target: dev
#    restart: always
#    env_file:
#      - ./.env
#    command: [ 'yarn', 'start' ]
#    volumes:
#      - '/usr/src/app/node_modules'
#    ports:
#      - '4000:4000'

volumes:
  redis-data:
    driver: local
